// leave off @2x/@3x
const images = {
  kmfLogo: require('../Images/logo.png'),
  background: require('../Images/BG.jpg'),
  background1: require('../Images/BG.png'),
  api: require('../Images/Icons/icon-api-testing.png'),
  components: require('../Images/Icons/icon-components.png'),
  deviceInfo: require('../Images/Icons/icon-device-information.png'),
  faq: require('../Images/Icons/faq-icon.png'),
  home: require('../Images/Icons/icon-home.png'),
  theme: require('../Images/Icons/icon-theme.png'),
  usageExamples: require('../Images/Icons/icon-usage-examples.png'),
  chevronRight: require('../Images/Icons/chevron-right.png'),
  hamburger: require('../Images/Icons/hamburger.png'),
  backButton: require('../Images/Icons/back-button.png'),
  closeButton: require('../Images/Icons/close-button.png'),
  billMurrary: require('../Images/artistSample.jpg'),
  flamingYoga: require('../Images/workshopSample.jpg'),
  alexbanks: require('../Images/artistpics/alexbanks.jpg'),
  detoxunit: require('../Images/artistpics/detoxunit.jpg'),
  devinkroes: require('../Images/artistpics/devinkroes.jpg'),
  dirtwire: require('../Images/artistpics/dirtwire.jpg'),
  djedi: require('../Images/artistpics/djedi.jpg'),
  evancasey: require('../Images/artistpics/evancasey.jpg'),
  fivealarm: require('../Images/artistpics/fivealarm.png'),
  goopsteppa: require('../Images/artistpics/goopsteppa.jpg'),
  ives: require('../Images/artistpics/ives.png'),
  kissee: require('../Images/artistpics/kissee.jpg'),
  librarian: require('../Images/artistpics/librarian.jpg'),
  longwalk: require('../Images/artistpics/longwalk.jpg'),
  lukemandala: require('../Images/artistpics/lukemandala.jpg'),
  manahan: require('../Images/artistpics/manahan.png'),
  marbs: require('../Images/artistpics/marbs.jpg'),
  matthealien: require('../Images/artistpics/matthealien.jpg'),
  olivier: require('../Images/artistpics/oliviergiacomotto.jpg'),
  porkchop: require('../Images/artistpics/porkchop.jpg'),
  spacegeisha: require('../Images/artistpics/spacegeisha.jpg'),
  tarabrooks: require('../Images/artistpics/tarabrooks.jpg'),
  thelem: require('../Images/artistpics/thelem.jpg'),
  frameworks: require('../Images/artistpics/frameworks.jpg'),
  splitjaxta: require('../Images/artistpics/splitjaxta.jpg'),
  diggler: require('../Images/artistpics/diggler.jpg'),
  keota: require('../Images/artistpics/keota.jpg'),
  brodyizm: require('../Images/artistpics/brodyizm.jpg'),
  triode: require('../Images/artistpics/triode.jpg'),
  joshvolt: require('../Images/artistpics/joshvolt.jpg'),
  evolushawn: require('../Images/artistpics/evolushawn.jpg'),
  rhythmic: require('../Images/artistpics/rhythmic.jpg'),
  kcnova: require('../Images/artistpics/kcnova.jpg'),
  stormshadow: require('../Images/artistpics/stormshadow.jpg'),
  dirtyworks: require('../Images/artistpics/dirtyworks.jpg'),
  dayne5150: require('../Images/artistpics/dayne5150.jpg'),
  deeveaux: require('../Images/artistpics/deeveaux.jpg'),
  cloudest: require('../Images/artistpics/cloudest.jpg'),
  styles: require('../Images/artistpics/styles.jpg'),
  strand: require('../Images/artistpics/strand.jpg'),
  noprophit: require('../Images/artistpics/noprophit.jpg'),
  woh: require('../Images/artistpics/woh.jpg'),
  modest: require('../Images/artistpics/modest.png'),
  phynix: require('../Images/artistpics/phynix.jpg'),
  dsqise: require('../Images/artistpics/dsqise.png'),
  redfx: require('../Images/artistpics/redfx.jpg'),
  beanboy: require('../Images/artistpics/beanboy.jpg'),

}

export default images
